[package]
name = "hopes"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["std", "alloc"] }
toml = "0.8"

[profile.dev]
opt-level = 0
debug = 0
incremental = true
codegen-units = 256

[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
panic = "abort"
strip = true

[profile.test]
opt-level = 0
debug = 0


